language: node_js
node_js:
  - lts/*
install:
  - yarn install # npm ci
  - yarn add vuepress # 安装
script:
  - yarn docs:build # npm run docs:build
after_success:
  - cd docs/.vuepress/dist
  - echo 'haier.wiki' > CNAME # CNAME
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: $GITHUB_TOKEN # 在 GitHub 中生成，用于允许 Travis 向你的仓库推送代码。在 Travis 的项目设置页面进行配置，设置为 secure variable
  target-branch: master # 集成发布到master分支
  keep_history: true
  on:
    branch: travis-ci